package kr.mooner510.ui

import android.content.pm.ApplicationInfo
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import kr.mooner510.appGraph
import kr.mooner510.data.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

private data class InstalledApp(val label:String,val packageName:String)
@Composable fun PinsAndRulesScreen(){val context=LocalContext.current;val graph=context.appGraph;val scope=rememberCoroutineScope();var rules by remember{mutableStateOf(emptyList<NotificationRule>())};var templates by remember{mutableStateOf(emptyList<PinTemplate>())};var edit by remember{mutableStateOf<NotificationRule?>(null)};var ruleOpen by remember{mutableStateOf(false)};var templateOpen by remember{mutableStateOf(false)};suspend fun reload(){rules=graph.repository.notificationRules();templates=graph.repository.pinTemplates()};LaunchedEffect(Unit){reload()};LazyColumn(Modifier.fillMaxSize().padding(horizontal=16.dp)){item{Text("압정 템플릿",style=MaterialTheme.typography.headlineSmall,modifier=Modifier.padding(top=20.dp));Text("Galaxy 모드 및 루틴의 앱 동작에서 실행할 수 있습니다.");Button({templateOpen=true},Modifier.padding(vertical=8.dp)){Text("템플릿 추가")}};items(templates,key={it.id}){t->Row(Modifier.fillMaxWidth().padding(vertical=10.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(t.name);Text(t.text)};TextButton({scope.launch{graph.repository.deletePinTemplate(t.id);graph.routineShortcutManager.refresh();reload()}}){Text("삭제")}};HorizontalDivider()};item{Text("알림 기록 규칙",style=MaterialTheme.typography.headlineSmall,modifier=Modifier.padding(top=24.dp));Text("제외 regex가 우선하며 포함 regex가 비어 있으면 선택 앱의 모든 알림을 기록합니다.");Button({edit=null;ruleOpen=true},Modifier.padding(vertical=8.dp)){Text("규칙 추가")}};items(rules,key={it.id}){r->Row(Modifier.fillMaxWidth().clickable{edit=r;ruleOpen=true}.padding(vertical=10.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(r.name);Text("앱 ${r.packageNames.size}개 · 포함 ${r.includeRegex.ifBlank{"전체"}} · 제외 ${r.excludeRegex.ifBlank{"없음"}}")};Switch(r.enabled,{v->scope.launch{graph.repository.upsertNotificationRule(r.copy(enabled=v));reload()}})};HorizontalDivider()}};if(templateOpen)TemplateDialog({templateOpen=false}){name,text->scope.launch{graph.repository.upsertPinTemplate(PinTemplate(name=name,text=text));graph.routineShortcutManager.refresh();templateOpen=false;reload()}};if(ruleOpen)RuleDialog(edit,{ruleOpen=false},edit?.let{r->{{scope.launch{graph.repository.deleteNotificationRule(r.id);ruleOpen=false;reload()}}}}){r->scope.launch{graph.repository.upsertNotificationRule(r);ruleOpen=false;reload()}}}
@Composable private fun TemplateDialog(onDismiss:()->Unit,onSave:(String,String)->Unit){var name by remember{mutableStateOf("")};var text by remember{mutableStateOf("")};AlertDialog(onDismiss,title={Text("루틴 압정 템플릿")},text={Column{OutlinedTextField(name,{name=it},label={Text("이름")});OutlinedTextField(text,{text=it},label={Text("기록 내용")})}},confirmButton={Button({onSave(name.trim(),text.trim())},enabled=name.isNotBlank()){Text("저장")}},dismissButton={TextButton(onDismiss){Text("취소")}})}
@Composable private fun RuleDialog(initial:NotificationRule?,onDismiss:()->Unit,onDelete:(()->Unit)?,onSave:(NotificationRule)->Unit){val context=LocalContext.current;var name by remember(initial){mutableStateOf(initial?.name?:"")};var include by remember(initial){mutableStateOf(initial?.includeRegex?:"")};var exclude by remember(initial){mutableStateOf(initial?.excludeRegex?:"")};var selected by remember(initial){mutableStateOf(initial?.packageNames?:emptySet())};var picker by remember{mutableStateOf(false)};val includeValid=include.isBlank()||runCatching{Regex(include)}.isSuccess;val excludeValid=exclude.isBlank()||runCatching{Regex(exclude)}.isSuccess;AlertDialog(onDismiss,title={Text(if(initial==null)"알림 규칙 추가" else "알림 규칙 수정")},text={Column{OutlinedTextField(name,{name=it},label={Text("규칙 이름")},modifier=Modifier.fillMaxWidth());OutlinedButton({picker=true},Modifier.fillMaxWidth()){Text("대상 앱 ${selected.size}개 선택")};OutlinedTextField(include,{include=it},label={Text("포함 regex (빈 값 = 전체)")},isError=!includeValid,modifier=Modifier.fillMaxWidth());OutlinedTextField(exclude,{exclude=it},label={Text("제외 regex")},isError=!excludeValid,modifier=Modifier.fillMaxWidth());onDelete?.let{TextButton(it){Text("규칙 삭제")}}}},confirmButton={Button({onSave(NotificationRule(id=initial?.id?:java.util.UUID.randomUUID().toString(),name=name.trim().ifBlank{"알림 규칙"},packageNames=selected,includeRegex=include,excludeRegex=exclude,enabled=initial?.enabled?:true))},enabled=selected.isNotEmpty()&&includeValid&&excludeValid){Text("저장")}},dismissButton={TextButton(onDismiss){Text("취소")}});if(picker)AppPicker(initial=selected,onDismiss={picker=false},onDone={selected=it;picker=false})}
@Composable private fun AppPicker(initial:Set<String>,onDismiss:()->Unit,onDone:(Set<String>)->Unit){val context=LocalContext.current;var apps by remember{mutableStateOf(emptyList<InstalledApp>())};var chosen by remember{mutableStateOf(initial)};var query by remember{mutableStateOf("")};LaunchedEffect(Unit){apps=withContext(Dispatchers.IO){context.packageManager.getInstalledApplications(0).filter{it.flags and ApplicationInfo.FLAG_SYSTEM==0||it.packageName==context.packageName}.map{InstalledApp(context.packageManager.getApplicationLabel(it).toString(),it.packageName)}.sortedBy{it.label.lowercase()}}};AlertDialog(onDismiss,title={Text("대상 앱")},text={Column{OutlinedTextField(query,{query=it},label={Text("검색")},modifier=Modifier.fillMaxWidth());LazyColumn(Modifier.heightIn(max=420.dp)){items(apps.filter{query.isBlank()||it.label.contains(query,true)||it.packageName.contains(query,true)},key={it.packageName}){a->Row(Modifier.fillMaxWidth().clickable{chosen=if(a.packageName in chosen)chosen-a.packageName else chosen+a.packageName}.padding(vertical=6.dp),verticalAlignment=Alignment.CenterVertically){Checkbox(a.packageName in chosen,null);Column{Text(a.label);Text(a.packageName)}}}}}},confirmButton={Button({onDone(chosen)}){Text("완료")}},dismissButton={TextButton(onDismiss){Text("취소")}})}
