package kr.mooner510.ui

import android.content.Intent
import android.graphics.Color
import android.net.Uri
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.clickable
import androidx.compose.foundation.gestures.detectDragGestures
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.compose.ui.viewinterop.AndroidView
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import kr.mooner510.appGraph
import kr.mooner510.data.*
import kotlinx.coroutines.launch
import org.maplibre.android.annotations.MarkerOptions
import org.maplibre.android.annotations.PolylineOptions
import org.maplibre.android.camera.CameraUpdateFactory
import org.maplibre.android.geometry.LatLng
import org.maplibre.android.maps.MapView
import java.time.*
import java.time.format.DateTimeFormatter
import kotlin.math.absoluteValue

private val timeFormatter=DateTimeFormatter.ofPattern("HH:mm")
@Composable fun TimelineScreen(){val context=LocalContext.current;val graph=context.appGraph;val scope=rememberCoroutineScope();val settings by graph.preferences.settings.collectAsStateWithLifecycle(initialValue=AppSettings());var date by remember{mutableStateOf(LocalDate.now())};var points by remember{mutableStateOf(emptyList<TrackPoint>())};var events by remember{mutableStateOf(emptyList<TimelineEvent>())};var selectedTime by remember{mutableLongStateOf(System.currentTimeMillis())};var pin by remember{mutableStateOf(false)};suspend fun reload(){points=graph.repository.trackPointsForDay(date);events=graph.repository.eventsForDay(date);val z=ZoneId.systemDefault();val start=date.atStartOfDay(z).toInstant().toEpochMilli();val end=date.plusDays(1).atStartOfDay(z).toInstant().toEpochMilli()-1;selectedTime=if(date==LocalDate.now())System.currentTimeMillis().coerceIn(start,end) else end};LaunchedEffect(date){reload()};LaunchedEffect(Unit){graph.repository.changes.collect{reload()}};Box(Modifier.fillMaxSize()){Column(Modifier.fillMaxSize()){Row(Modifier.fillMaxWidth().padding(12.dp),horizontalArrangement=Arrangement.SpaceBetween,verticalAlignment=Alignment.CenterVertically){TextButton({date=date.minusDays(1)}){Text("‹")};Text(date.toString());TextButton({date=date.plusDays(1).coerceAtMost(LocalDate.now())}){Text("›")}};TimelineMap(Modifier.weight(1f).fillMaxWidth(),points,events,selectedTime,settings.mapStyleUri);SelectedEventStrip(events,selectedTime);TimeRuler(date,selectedTime,events){selectedTime=it}};FloatingActionButton({pin=true},Modifier.align(Alignment.BottomEnd).padding(20.dp)){Text("＋")}};if(pin)ManualPinDialog({pin=false}){text->scope.launch{val now=System.currentTimeMillis();val p=graph.repository.latestTrackPoint()?.takeIf{now-it.timestamp<=300000};graph.repository.insertEvent(TimelineEvent(timestamp=now,type=EventType.PIN_MANUAL,latitude=p?.latitude,longitude=p?.longitude,title="압정",body=text,source="MANUAL"));pin=false}}}
@Composable private fun TimelineMap(modifier:Modifier,points:List<TrackPoint>,events:List<TimelineEvent>,selectedTime:Long,styleUri:String){val context=LocalContext.current;val relevant=remember(events,selectedTime){events.filter{(it.timestamp-selectedTime).absoluteValue<=90000&&it.latitude!=null&&it.longitude!=null}};AndroidView(modifier=modifier,factory={MapView(context).apply{onCreate(null);onStart();getMapAsync{it.setStyle(styleUri)}}},update={v->v.getMapAsync{m->if(m.style==null)m.setStyle(styleUri){drawTimeline(m,points,relevant,selectedTime)}else drawTimeline(m,points,relevant,selectedTime)}})}
private fun drawTimeline(map:org.maplibre.android.maps.MapLibreMap,points:List<TrackPoint>,events:List<TimelineEvent>,selectedTime:Long){map.clear();val twelve=points.filter{it.timestamp in(selectedTime-12*60*60_000L)..selectedTime};val old=twelve.filter{it.timestamp<selectedTime-2*60*60_000L};val recent=twelve.filter{it.timestamp>=selectedTime-2*60*60_000L};splitAtGaps(old).forEach{s->if(s.size>=2)map.addPolyline(PolylineOptions().addAll(s.map{LatLng(it.latitude,it.longitude)}).color(Color.argb(75,40,110,220)).width(5f))};splitAtGaps(recent).forEach{s->if(s.size>=2)map.addPolyline(PolylineOptions().addAll(s.map{LatLng(it.latitude,it.longitude)}).color(Color.rgb(35,105,235)).width(7f))};points.minByOrNull{(it.timestamp-selectedTime).absoluteValue}?.takeIf{(it.timestamp-selectedTime).absoluteValue<=600000}?.let{map.addMarker(MarkerOptions().position(LatLng(it.latitude,it.longitude)).title("선택 시각 ${formatTime(selectedTime)}"));if(twelve.isNotEmpty())map.animateCamera(CameraUpdateFactory.newLatLng(LatLng(it.latitude,it.longitude)))};events.forEach{map.addMarker(MarkerOptions().position(LatLng(it.latitude!!,it.longitude!!)).title(it.title).snippet(it.body?:formatTime(it.timestamp)))}}
private fun splitAtGaps(points:List<TrackPoint>,maxGapMs:Long=300000):List<List<TrackPoint>>{if(points.isEmpty())return emptyList();val out=mutableListOf<MutableList<TrackPoint>>();var current=mutableListOf(points.first());out+=current;for(p in points.drop(1)){if(p.timestamp-current.last().timestamp>maxGapMs){current=mutableListOf();out+=current};current+=p};return out}
@Composable private fun TimeRuler(date:LocalDate,selectedTime:Long,events:List<TimelineEvent>,onTime:(Long)->Unit){val z=ZoneId.systemDefault();val start=date.atStartOfDay(z).toInstant().toEpochMilli();val end=date.plusDays(1).atStartOfDay(z).toInstant().toEpochMilli()-1;Column(Modifier.fillMaxWidth().padding(bottom=8.dp)){Text(formatTime(selectedTime),Modifier.align(Alignment.CenterHorizontally));Canvas(Modifier.fillMaxWidth().height(82.dp).pointerInput(start,end,selectedTime){detectDragGestures{change,drag->change.consume();val delta=(-drag.x/size.width.toFloat()*6*60*60_000L).toLong();onTime((selectedTime+delta).coerceIn(start,end))}}){val center=size.width/2f;val ppm=size.width/(6f*60f);val minute=selectedTime/60000L;for(o in -180..180 step 5){val x=center+o*ppm;val abs=minute+o;val major=abs%60L==0L;val half=abs%30L==0L;val h=if(major)32f else if(half)22f else 12f;drawLine(androidx.compose.ui.graphics.Color.Gray,Offset(x,size.height-h),Offset(x,size.height),if(major)2f else 1f)};events.forEach{val d=(it.timestamp-selectedTime)/60000f;if(d in -180f..180f)drawCircle(androidx.compose.ui.graphics.Color(0xFFEF5350),5f,Offset(center+d*ppm,12f))};drawLine(androidx.compose.ui.graphics.Color.Black,Offset(center,0f),Offset(center,size.height),4f,StrokeCap.Round)}}}
@Composable private fun SelectedEventStrip(events:List<TimelineEvent>,selectedTime:Long){val context=LocalContext.current;val graph=context.appGraph;val scope=rememberCoroutineScope();val nearby=remember(events,selectedTime){events.filter{(it.timestamp-selectedTime).absoluteValue<=90000}.sortedBy{(it.timestamp-selectedTime).absoluteValue}};var detail by remember{mutableStateOf<TimelineEvent?>(null)};nearby.firstOrNull()?.let{e->Card(Modifier.fillMaxWidth().padding(12.dp,4.dp).clickable{detail=e}){Column(Modifier.padding(12.dp)){Text("📌 ${e.title} · ${formatTime(e.timestamp)}");e.body?.let{Text(it,maxLines=2)};if(nearby.size>1)Text("같은 시각 주변 기록 ${nearby.size}개")}}};detail?.let{e->var attachments by remember(e.id){mutableStateOf(emptyList<AttachmentRecord>())};LaunchedEffect(e.id){attachments=graph.repository.attachmentsForEvent(e.id)};AlertDialog({detail=null},title={Text(e.title)},text={Column{Text(formatTime(e.timestamp));e.body?.let{Text(it)};attachments.forEach{a->if(!a.externalUri.isNullOrBlank())Row(verticalAlignment=Alignment.CenterVertically){Text(a.kind,Modifier.weight(1f));TextButton({runCatching{context.startActivity(Intent(Intent.ACTION_VIEW).apply{setDataAndType(Uri.parse(a.externalUri),a.mimeType?:"audio/*");addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)})}}){Text("열기")};TextButton({scope.launch{runCatching{context.contentResolver.openInputStream(Uri.parse(a.externalUri))?.use{graph.repository.addEncryptedAttachment(e.id,"${a.kind}_IMPORTED",a.mimeType,it)}};attachments=graph.repository.attachmentsForEvent(e.id)}}){Text("보관")}}else Text("${a.kind} · 암호화 보관됨")}}},confirmButton={TextButton({detail=null}){Text("닫기")}})}}
@Composable private fun ManualPinDialog(onDismiss:()->Unit,onSave:(String)->Unit){var text by remember{mutableStateOf("")};AlertDialog(onDismiss,title={Text("현재 위치에 압정")},text={OutlinedTextField(text,{text=it},label={Text("기록")},minLines=3)},confirmButton={Button({onSave(text.trim())},enabled=text.isNotBlank()){Text("기록")}},dismissButton={TextButton(onDismiss){Text("취소")}})}
private fun formatTime(ms:Long)=Instant.ofEpochMilli(ms).atZone(ZoneId.systemDefault()).format(timeFormatter)
