package kr.mooner510.map

import android.content.Context
import kr.mooner510.data.PreferencesStore
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import org.json.JSONObject
import org.maplibre.android.geometry.LatLngBounds
import org.maplibre.android.offline.*
import java.util.UUID

sealed interface OfflineDownloadState{data object Idle:OfflineDownloadState;data class Downloading(val name:String,val completed:Long,val required:Long,val bytes:Long):OfflineDownloadState;data class Complete(val name:String,val bytes:Long):OfflineDownloadState;data class Failed(val message:String):OfflineDownloadState}
data class OfflineRegionInfo(val id:Long,val name:String,val completedResources:Long,val requiredResources:Long,val completedBytes:Long)
class OfflineMapManager(private val context:Context,private val preferences:PreferencesStore){private val manager by lazy{OfflineManager.getInstance(context)};private val _downloadState=MutableStateFlow<OfflineDownloadState>(OfflineDownloadState.Idle);val downloadState=_downloadState.asStateFlow()
 suspend fun download(name:String,north:Double,east:Double,south:Double,west:Double,minZoom:Double=5.0,maxZoom:Double=16.0){val style=preferences.current().mapStyleUri;val d=OfflineTilePyramidRegionDefinition(style,LatLngBounds.from(north,east,south,west),minZoom,maxZoom,context.resources.displayMetrics.density.coerceIn(1f,3f),true);val meta=JSONObject().apply{put("id",UUID.randomUUID().toString());put("name",name);put("createdAt",System.currentTimeMillis())}.toString().toByteArray();manager.createOfflineRegion(d,meta,object:OfflineManager.CreateOfflineRegionCallback{override fun onCreate(r:OfflineRegion){r.setObserver(object:OfflineRegion.OfflineRegionObserver{override fun onStatusChanged(s:OfflineRegionStatus){_downloadState.value=if(s.isComplete)OfflineDownloadState.Complete(name,s.completedResourceSize) else OfflineDownloadState.Downloading(name,s.completedResourceCount,s.requiredResourceCount,s.completedResourceSize)};override fun onError(e:OfflineRegionError){_downloadState.value=OfflineDownloadState.Failed("${e.reason}: ${e.message}")};override fun mapboxTileCountLimitExceeded(limit:Long){_downloadState.value=OfflineDownloadState.Failed("오프라인 타일 제한 초과: $limit")}});r.setDownloadState(OfflineRegion.STATE_ACTIVE)};override fun onError(error:String){_downloadState.value=OfflineDownloadState.Failed(error)}})}
 fun list(callback:(List<OfflineRegionInfo>)->Unit){manager.listOfflineRegions(object:OfflineManager.ListOfflineRegionsCallback{override fun onList(regions:Array<OfflineRegion>?){val rs=regions.orEmpty();if(rs.isEmpty()){callback(emptyList());return};val out=mutableListOf<OfflineRegionInfo>();var left=rs.size;rs.forEach{r->r.getStatus(object:OfflineRegion.OfflineRegionStatusCallback{override fun onStatus(s:OfflineRegionStatus){out+=OfflineRegionInfo(r.id,metadataName(r.metadata),s.completedResourceCount,s.requiredResourceCount,s.completedResourceSize);if(--left==0)callback(out.sortedBy{it.name})};override fun onError(error:String){if(--left==0)callback(out.sortedBy{it.name})}})}};override fun onError(error:String){callback(emptyList())}})}
 fun delete(id:Long,onDone:(Boolean)->Unit){manager.getOfflineRegion(id,object:OfflineManager.GetOfflineRegionCallback{override fun onRegion(r:OfflineRegion){r.delete(object:OfflineRegion.OfflineRegionDeleteCallback{override fun onDelete()=onDone(true);override fun onError(error:String)=onDone(false)})};override fun onRegionNotFound()=onDone(false);override fun onError(error:String)=onDone(false)})};private fun metadataName(b:ByteArray)=runCatching{JSONObject(b.toString(Charsets.UTF_8)).optString("name","오프라인 지도")}.getOrDefault("오프라인 지도")}
