package kr.mooner510.events

import android.Manifest
import android.content.*
import android.content.pm.PackageManager
import android.database.ContentObserver
import android.net.Uri
import android.os.Handler
import android.os.Looper
import android.provider.Telephony
import androidx.core.content.ContextCompat
import kr.mooner510.appGraph
import kr.mooner510.data.*
import kotlinx.coroutines.*
import java.io.BufferedReader
import java.io.InputStreamReader

class MessageObserver(private val context:Context,private val repository:NodeMapRepository,private val scope:CoroutineScope){
 private val smsObserver=object:ContentObserver(Handler(Looper.getMainLooper())){override fun onChange(selfChange:Boolean,uri:Uri?){scope.launch{syncSms(false)}}};private val mmsObserver=object:ContentObserver(Handler(Looper.getMainLooper())){override fun onChange(selfChange:Boolean,uri:Uri?){scope.launch{syncMms(false)}}}
 fun start(){if(!hasReadSms())return;context.contentResolver.registerContentObserver(Telephony.Sms.CONTENT_URI,true,smsObserver);context.contentResolver.registerContentObserver(Telephony.Mms.CONTENT_URI,true,mmsObserver);scope.launch{initialize("last_sms_id",Telephony.Sms.CONTENT_URI);initialize("last_mms_id",Telephony.Mms.CONTENT_URI)}}
 fun stop(){runCatching{context.contentResolver.unregisterContentObserver(smsObserver)};runCatching{context.contentResolver.unregisterContentObserver(mmsObserver)}}
 suspend fun syncSms(triggeredByBroadcast:Boolean){if(!hasReadSms())return;if(repository.state("last_sms_id")==null){val max=maxId(Telephony.Sms.CONTENT_URI);repository.setState("last_sms_id",if(triggeredByBroadcast)(max-1).coerceAtLeast(0).toString() else max.toString());if(!triggeredByBroadcast)return};val last=repository.state("last_sms_id")?.toLongOrNull()?:0;val c=context.contentResolver.query(Telephony.Sms.CONTENT_URI,arrayOf(Telephony.Sms._ID,Telephony.Sms.ADDRESS,Telephony.Sms.BODY,Telephony.Sms.DATE,Telephony.Sms.TYPE),"${Telephony.Sms._ID} > ?",arrayOf(last.toString()),"${Telephony.Sms._ID} ASC")?:return;var newest=last;c.use{r->while(r.moveToNext()){val id=r.getLong(0);newest=maxOf(newest,id);val address=r.getString(1).orEmpty();val body=r.getString(2).orEmpty();val ts=r.getLong(3).takeIf{it>0}?:System.currentTimeMillis();val type=r.getInt(4);val direction=when(type){Telephony.Sms.MESSAGE_TYPE_INBOX->"수신";Telephony.Sms.MESSAGE_TYPE_SENT->"발신";Telephony.Sms.MESSAGE_TYPE_OUTBOX->"발신 대기";else->"메시지"};val name=ContactResolver.displayName(context,address);val p=repository.nearestTrackPoint(ts);repository.insertEvent(TimelineEvent(timestamp=ts,type=EventType.SMS,latitude=p?.latitude,longitude=p?.longitude,title="$direction SMS · ${name?:address.ifBlank{"알 수 없음"}}",body=body.takeIf{it.isNotBlank()},source="android.provider.Telephony.Sms",metadata=mapOf("providerId" to id.toString(),"address" to address,"contactName" to(name?:""),"direction" to direction,"messageType" to type.toString()).filterValues{it.isNotBlank()}))}};if(newest>last)repository.setState("last_sms_id",newest.toString())}
 suspend fun syncMms(triggeredByBroadcast:Boolean){if(!hasReadSms())return;if(repository.state("last_mms_id")==null){val max=maxId(Telephony.Mms.CONTENT_URI);repository.setState("last_mms_id",if(triggeredByBroadcast)(max-1).coerceAtLeast(0).toString() else max.toString());if(!triggeredByBroadcast)return};val last=repository.state("last_mms_id")?.toLongOrNull()?:0;val c=context.contentResolver.query(Telephony.Mms.CONTENT_URI,arrayOf(Telephony.Mms._ID,Telephony.Mms.DATE,Telephony.Mms.MESSAGE_BOX,Telephony.Mms.SUBJECT),"${Telephony.Mms._ID} > ?",arrayOf(last.toString()),"${Telephony.Mms._ID} ASC")?:return;var newest=last;c.use{r->while(r.moveToNext()){val id=r.getLong(0);newest=maxOf(newest,id);val ts=r.getLong(1).let{if(it<10_000_000_000L)it*1000L else it};val box=r.getInt(2);val subject=r.getString(3).orEmpty();val direction=when(box){Telephony.Mms.MESSAGE_BOX_INBOX->"수신";Telephony.Mms.MESSAGE_BOX_SENT->"발신";Telephony.Mms.MESSAGE_BOX_OUTBOX->"발신 대기";else->"메시지"};val address=mmsAddress(id,box);val name=ContactResolver.displayName(context,address);val body=mmsText(id).ifBlank{subject};val p=repository.nearestTrackPoint(ts);repository.insertEvent(TimelineEvent(timestamp=ts,type=EventType.MMS,latitude=p?.latitude,longitude=p?.longitude,title="$direction MMS · ${name?:address.ifBlank{"알 수 없음"}}",body=body.takeIf{it.isNotBlank()},source="android.provider.Telephony.Mms",metadata=mapOf("providerId" to id.toString(),"address" to address,"contactName" to(name?:""),"direction" to direction,"messageBox" to box.toString(),"subject" to subject).filterValues{it.isNotBlank()}))}};if(newest>last)repository.setState("last_mms_id",newest.toString())}
 private fun mmsAddress(id:Long,box:Int):String{val wanted=if(box==Telephony.Mms.MESSAGE_BOX_INBOX)137 else 151;return context.contentResolver.query(Uri.parse("content://mms/$id/addr"),arrayOf("address","type"),null,null,null)?.use{c->buildList{while(c.moveToNext()){val a=c.getString(0).orEmpty();if(c.getInt(1)==wanted&&a!="insert-address-token")add(a)}}.joinToString(", ")}.orEmpty()}
 private fun mmsText(id:Long):String=context.contentResolver.query(Uri.parse("content://mms/part"),arrayOf("_id","ct","text","_data"),"mid = ? AND ct = ?",arrayOf(id.toString(),"text/plain"),null)?.use{c->buildList{while(c.moveToNext()){val part=c.getString(0);val text=c.getString(2);val data=c.getString(3);when{!text.isNullOrBlank()->add(text);!data.isNullOrBlank()->runCatching{context.contentResolver.openInputStream(Uri.parse("content://mms/part/$part"))?.use{BufferedReader(InputStreamReader(it)).readText()}}.getOrNull()?.takeIf{it.isNotBlank()}?.let(::add)}}}.joinToString("\n")}.orEmpty()
 private suspend fun initialize(k:String,u:Uri){if(repository.state(k)==null)repository.setState(k,maxId(u).toString())};private fun maxId(u:Uri):Long=context.contentResolver.query(u,arrayOf("MAX(_id)"),null,null,null)?.use{if(it.moveToFirst())it.getLong(0) else 0}?:0;private fun hasReadSms()=ContextCompat.checkSelfPermission(context,Manifest.permission.READ_SMS)==PackageManager.PERMISSION_GRANTED
}
class SmsReceiver:BroadcastReceiver(){override fun onReceive(context:Context,intent:Intent){if(intent.action!=Telephony.Sms.Intents.SMS_RECEIVED_ACTION)return;val p=goAsync();CoroutineScope(SupervisorJob()+Dispatchers.IO).launch{try{MessageObserver(context,context.appGraph.repository,this).syncSms(true)}finally{p.finish()}}}}
class MmsReceiver:BroadcastReceiver(){override fun onReceive(context:Context,intent:Intent){if(intent.action!=Telephony.Sms.Intents.WAP_PUSH_RECEIVED_ACTION)return;val p=goAsync();CoroutineScope(SupervisorJob()+Dispatchers.IO).launch{try{MessageObserver(context,context.appGraph.repository,this).syncMms(true)}finally{p.finish()}}}}
