package kr.mooner510.backup

import android.content.Context
import android.net.Uri
import kr.mooner510.data.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONObject
import java.io.*
import java.security.SecureRandom
import java.time.Instant
import java.util.zip.ZipEntry
import java.util.zip.ZipInputStream
import java.util.zip.ZipOutputStream
import javax.crypto.Cipher
import javax.crypto.CipherInputStream
import javax.crypto.CipherOutputStream
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.PBEKeySpec
import javax.crypto.spec.SecretKeySpec

class BackupManager(private val context:Context,private val repository:NodeMapRepository,private val attachmentStore:AttachmentStore){
 suspend fun export(destination:Uri,password:CharArray)=withContext(Dispatchers.IO){require(password.size>=8){"백업 비밀번호는 8자 이상이어야 합니다."};val temp=File.createTempFile("nodemap-export-",".zip",context.cacheDir);try{ZipOutputStream(BufferedOutputStream(FileOutputStream(temp))).use{z->writeText(z,"manifest.json",JSONObject().apply{put("format","nodemap");put("version",1);put("createdAt",Instant.now().toEpochMilli())}.toString());writeLines(z,"track_points.jsonl",repository.allTrackPoints().map{it.exportJson().toString()});writeLines(z,"events.jsonl",repository.allEvents().map{it.exportJson().toString()});writeLines(z,"notification_rules.jsonl",repository.notificationRules().map{JSONObject().apply{put("id",it.id);put("payload",it.toJson())}.toString()});writeLines(z,"pin_templates.jsonl",repository.pinTemplates().map{JSONObject().apply{put("id",it.id);put("payload",it.toJson())}.toString()});val attachments=repository.allAttachments();writeLines(z,"attachments.jsonl",attachments.map{it.exportJson().toString()});attachments.forEach{a->openAttachment(a)?.use{i->z.putNextEntry(ZipEntry("attachments/${a.id}"));i.copyTo(z);z.closeEntry()}}};context.contentResolver.openOutputStream(destination,"w")!!.use{out->FileInputStream(temp).use{encryptPortable(it,out,password)}}}finally{password.fill('\u0000');temp.delete()}}
 suspend fun restore(source:Uri,password:CharArray)=withContext(Dispatchers.IO){require(password.size>=8);val temp=File.createTempFile("nodemap-restore-",".zip",context.cacheDir);val unpack=File(context.cacheDir,"nodemap-restore-${System.nanoTime()}").apply{mkdirs()};try{context.contentResolver.openInputStream(source)!!.use{i->FileOutputStream(temp).use{decryptPortable(i,it,password)}};unzipSafely(temp,unpack);val manifest=JSONObject(File(unpack,"manifest.json").readText());require(manifest.optString("format")=="nodemap"&&manifest.optInt("version")==1){"지원하지 않는 NodeMap 백업입니다."};val points=readJsonLines(File(unpack,"track_points.jsonl")).map(::trackPointFromExport);val events=readJsonLines(File(unpack,"events.jsonl")).map(::eventFromExport);val rules=readJsonLines(File(unpack,"notification_rules.jsonl")).map{NotificationRule.fromJson(it.getString("id"),it.getJSONObject("payload"))};val templates=readJsonLines(File(unpack,"pin_templates.jsonl")).map{PinTemplate.fromJson(it.getString("id"),it.getJSONObject("payload"))};val attachments=readJsonLines(File(unpack,"attachments.jsonl")).map(::attachmentFromExport);repository.clearForRestore();points.forEach{repository.insertTrackPoint(it.copy(id=0))};events.forEach{repository.insertEvent(it)};rules.forEach{repository.upsertNotificationRule(it)};templates.forEach{repository.upsertPinTemplate(it)};attachments.forEach{r->val f=File(unpack,"attachments/${r.id}");if(f.isFile)f.inputStream().use{repository.addEncryptedAttachment(r.eventId,r.kind,r.mimeType,it,r.id)}else if(!r.externalUri.isNullOrBlank())repository.addExternalAttachment(r.eventId,r.kind,r.mimeType,r.externalUri,r.id)}}finally{password.fill('\u0000');temp.delete();unpack.deleteRecursively()}}
 private fun openAttachment(r:AttachmentRecord):InputStream?=when{r.encryptedPath.isNotBlank()->runCatching{attachmentStore.open(r.encryptedPath)}.getOrNull();!r.externalUri.isNullOrBlank()->runCatching{context.contentResolver.openInputStream(Uri.parse(r.externalUri))}.getOrNull();else->null}
 private fun encryptPortable(input:InputStream,output:OutputStream,password:CharArray){val random=SecureRandom();val salt=ByteArray(16).also(random::nextBytes);val iv=ByteArray(12).also(random::nextBytes);val cipher=Cipher.getInstance("AES/GCM/NoPadding").apply{init(Cipher.ENCRYPT_MODE,deriveKey(password,salt),GCMParameterSpec(128,iv))};output.write(MAGIC);output.write(1);output.write(salt.size);output.write(salt);output.write(iv.size);output.write(iv);CipherOutputStream(output,cipher).use{input.copyTo(it)}}
 private fun decryptPortable(input:InputStream,output:OutputStream,password:CharArray){val b=BufferedInputStream(input);require(b.readNBytes(MAGIC.size).contentEquals(MAGIC));require(b.read()==1);val salt=b.readNBytes(b.read().also{require(it in 16..64)});val iv=b.readNBytes(b.read().also{require(it in 12..32)});val cipher=Cipher.getInstance("AES/GCM/NoPadding").apply{init(Cipher.DECRYPT_MODE,deriveKey(password,salt),GCMParameterSpec(128,iv))};CipherInputStream(b,cipher).use{it.copyTo(output)}}
 private fun deriveKey(password:CharArray,salt:ByteArray):SecretKeySpec{val spec=PBEKeySpec(password,salt,310_000,256);val bytes=SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(spec).encoded;spec.clearPassword();return SecretKeySpec(bytes,"AES")}
 private fun writeText(z:ZipOutputStream,name:String,text:String){z.putNextEntry(ZipEntry(name));z.write(text.toByteArray());z.closeEntry()};private fun writeLines(z:ZipOutputStream,name:String,lines:List<String>)=writeText(z,name,lines.joinToString("\n"));private fun readJsonLines(f:File)=if(!f.isFile)emptyList() else f.useLines{s->s.filter{it.isNotBlank()}.map(::JSONObject).toList()}
 private fun unzipSafely(zipFile:File,destination:File){ZipInputStream(BufferedInputStream(FileInputStream(zipFile))).use{z->while(true){val e=z.nextEntry?:break;val out=File(destination,e.name).canonicalFile;require(out.path.startsWith(destination.canonicalPath+File.separator));if(e.isDirectory)out.mkdirs()else{out.parentFile?.mkdirs();FileOutputStream(out).use{z.copyTo(it)}};z.closeEntry()}}}
 companion object{private val MAGIC="NODEMAP".toByteArray(Charsets.US_ASCII)}
}
private fun TrackPoint.exportJson()=JSONObject().apply{put("timestamp",timestamp);put("payload",toJson())};private fun trackPointFromExport(j:JSONObject)=TrackPoint.fromJson(0,j.getLong("timestamp"),j.getJSONObject("payload"));private fun TimelineEvent.exportJson()=JSONObject().apply{put("id",id);put("timestamp",timestamp);put("type",type.name);put("payload",toJson())};private fun eventFromExport(j:JSONObject)=TimelineEvent.fromJson(j.getString("id"),j.getLong("timestamp"),EventType.valueOf(j.getString("type")),j.getJSONObject("payload"));private fun AttachmentRecord.exportJson()=JSONObject().apply{put("id",id);put("eventId",eventId);put("kind",kind);mimeType?.let{put("mimeType",it)};put("createdAt",createdAt);externalUri?.let{put("externalUri",it)}};private fun attachmentFromExport(j:JSONObject)=AttachmentRecord(j.getString("id"),j.getString("eventId"),j.getString("kind"),j.optString("mimeType").takeIf{it.isNotBlank()},"",j.optLong("createdAt"),j.optString("externalUri").takeIf{it.isNotBlank()})
