name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  pipeline:
    uses: Mooner510/workflows/.github/workflows/pipeline.yml@b4e9fa4cfc47b2e6a49b44b7c53536eb0f389c18
    with:
      components: |
        [
          {
            "name": "android",
            "type": "java-kotlin",
            "path": ".",
            "profile": "android"
          }
        ]
