name: Release Android

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: production-nodemap-android
  cancel-in-progress: false

jobs:
  android:
    environment: production
    runs-on: [self-hosted, linux]
    timeout-minutes: 45
    steps:
      - uses: Mooner510/workflows/.github/actions/cd/android-production@b4e9fa4cfc47b2e6a49b44b7c53536eb0f389c18
        with:
          working-directory: .
